#+title: WaggleNet Cloud API

API infrastructure to interact with AWS services (e.g DynamoDB and Cognito).

** Requirements
Package requirements are specified in the src_sh[:exports code]{requirements.txt}. You will also need to create a .env configuration file with the necessary AWS access keys/information.

#+begin_sh options
--- /.env ---
COGNITO_CLIENT_ID=XXXXX

AWS_ACCESS_KEY_ID=XXXXX
AWS_SECRET_ACCESS_KEY=XXXX
#+end_sh

These parameters are supplied fed into the script at startup by Flask's dotenv implementation.

** Functions
This API has auth capabilities to register/login users, such that an access key can be obtained to either make a request to DynamoDB or to make an authenticated request to the DynamoDB functions of this API. The endpoints have been segregated below into Cognito and DynamoDB functions.
*** Cognito
**** User Registration
Self-explanatory.
- Endpoint: src_sh[:exports code]{/signup}.
- Methods: POST
- Argument format: JSON. Format demonstrated below
- Other notes: username must be an email. Password must have 8 chars minimum, >=1 uppercase letter, >=1 number, >=1 special symbol. A character can be consecutively repeated a maximum of 2 times.

#+begin_JSON options
{
  "user": "{EMAIL}",
  "pass": "{PASSWORD}"
}
#+end_JSON
